language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: de-jaggl
    token:
      secure: "XRtGmIUtQCMUb2m7TwerI7LH4MYUQewhSfbtM+6BzjiuZ+HT68BP5GP3FSCF4+xO47m9FVLGI8NyFQia/dURZSIEU7bbiqmHSaSg7XYeHpHo30qIt4s9FoDAIGflntsOldL3eYJZK0mE3y0b85LXMJl9eB/d5aZVLQDI6tGZUMLy5YxQCjoojBEjMivug7ATyMe4RKkWolY+yOsDxW4amujdTTDBzmhHLnPCaiAsJ1zbcEQUCEYrqjK+S4vfMvskyE554ywvU9lGBW2sT+HD4+gYG43RfDmazl9jxO9ER4gLNxtDuRk8OBJqOgBiKgC3PqoCYQ8wUI2sR9mlBBmjqPF6Zx/diUTg7Fo2v/MAOCPYc1bA6JEreaMLxVdZJt6HpzTThGqjyuQhBkP8d1hiMre8rDtNCGpW6ovMhpo86AfHOZav74lGhZwRZsLClc8XEMn/6/yvGOd/OICGVdwEx/npRX4HE98sfEf3eh3Q7/Wjd9dYbD7mWobULOWRGuk+EWhB/bUbSL50/FgewX+8XncB/8PbA1dNknhWhEM6rcp212Y4uulWrKFWvRRR/5gGkGVEm7hXqKjHH2u4G5uYWvBBSvNvzA3i68pMPjpd1pLrcSHP74go3A/3XHlDUw+5QcrZYOrAKnTfknEW1EnF1cju2TMLPQ1agAGCqy7+VBk="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=de-jaggl_sqlbuilder

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'